{{- with .Values.route }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    "helm.sh/hook": post-install,post-upgrade
  labels:
    {{- include "app.labels" $ | nindent 4 }}
  name: {{ include "app.fullname" $ }}
spec:
  {{- if .host }}
  host: {{ .host }}
  {{- end }}
  {{- if .path }}
  path: {{ .path }}
  {{- end }}
  port:
    targetPort: {{ $.Values.service.port }}
  to:
    kind: Service
    name: {{ include "app.fullname" $ }}
  wildcardPolicy: None
{{- end }}
