---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.app.name }}-pipeline
  namespace: {{ .Values.argocd.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  project: default
  source:
    repoURL: {{ .Values.argocd.repo_url }}
    targetRevision: {{ .Values.argocd.target_revision }}
    path: ./helm/build
    helm:
      parameters:
        - name: build.cluster_subdomain
          value: "{{ .Values.helm_params.build.cluster_subdomain}}"
        - name: build.maven.maven_builder_image
          value: "{{ .Values.helm_params.build.maven.maven_builder_image}}"
  destination:
    server: {{ .Values.dev.destination.server }}
    namespace: {{ .Values.dev.destination.namespace }}
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true    
    retry:
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy      
